[package]
name = "tallyman"
version = "0.1.0"
authors = ["George Lesica <george@lesica.com>", "Ken Youens-Clark <kyclark@arizona.edu>"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
multimap = "0.8.2"

[profile.release]
debug = true
